version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: libertea-mongodb
    hostname: libertea-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${PANEL_MONGODB_PASSWORD}
    volumes:
      - ./data/db:/data/db
    restart: always
    network_mode: host
    logging:
      options:
        max-size: 10m
  rsyslog:
    build: ./syslog
    hostname: libertea-rsyslog
    container_name: libertea-rsyslog
    restart: always
    ports:
      - "127.0.0.1:514:514/udp"
    volumes:
      - "./data/logs:/var/log/log"
    cap_add:
      - SYSLOG
    logging:
      options:
        max-size: 10m
  log-parser:
    build: ./log-parser
    container_name: libertea-log-parser
    volumes:
      - "./data/logs:/data/logs"
      - "./data/usages:/data/usages"
      - "./data/parsed-logs:/data/parsed-logs"
    restart: always
    logging:
      options:
        max-size: 10m
  haproxy:
    environment:
      - CONN_VLESS_WS_URL=${CONN_VLESS_WS_URL}
      - CONN_VLESS_WS_IP=${CONN_VLESS_WS_IP}
      - CONN_VMESS_WS_URL=${CONN_VMESS_WS_URL}
      - CONN_VMESS_WS_IP=${CONN_VMESS_WS_IP}
      - CONN_TROJAN_WS_URL=${CONN_TROJAN_WS_URL}
      - CONN_TROJAN_WS_IP=${CONN_TROJAN_WS_IP}
      - CONN_SHADOWSOCKS_V2RAY_URL=${CONN_SHADOWSOCKS_V2RAY_URL}
      - CONN_SHADOWSOCKS_V2RAY_IP=${CONN_SHADOWSOCKS_V2RAY_IP}
      - HOSTCONTROLLER_API_KEY=${HOSTCONTROLLER_API_KEY}
      - PANEL_ADMIN_UUID=${PANEL_ADMIN_UUID}
      - PANEL_ADMIN_PASSWORD=${PANEL_ADMIN_PASSWORD}
    build: ./haproxy
    container_name: libertea-haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/
      - ./haproxy/script.lua:/haproxy-files/script.lua
      - ./data/haproxy-lists:/haproxy-files/lists
      - /etc/ssl/ha-certs:/etc/ssl/ha-certs
      # - /var/lib/haproxy:/home/haproxy_stats
    restart: always
    network_mode: host
    logging:
      options:
        max-size: 10m
    depends_on:
      # - panel
      - log-parser
  provider-trojan-ws:
    environment:
      - FIREWALL_OUTBOUND_UDP_PORTS=${FIREWALL_OUTBOUND_UDP_PORTS}
      - FIREWALL_OUTBOUND_TCP_PORTS=${FIREWALL_OUTBOUND_TCP_PORTS}
    build: ./providers/trojan-ws
    ports:
      - "127.0.0.1:2001:2001"
      - "127.0.0.1:12001:12001"
    cap_add:
      - NET_ADMIN
    container_name: libertea-provider-trojan-ws
    restart: always
    volumes:
      - './providers/trojan-ws/config.json:/etc/xray/config.json'
      - './data/certs/selfsigned/cert.pem:/etc/xray/cert.pem:ro'
      - './data/certs/selfsigned/privkey.pem:/etc/xray/privkey.pem:ro'
  provider-vless-ws:
    environment:
      - FIREWALL_OUTBOUND_UDP_PORTS=${FIREWALL_OUTBOUND_UDP_PORTS}
      - FIREWALL_OUTBOUND_TCP_PORTS=${FIREWALL_OUTBOUND_TCP_PORTS}
    build: ./providers/vless-ws
    ports:
      - "127.0.0.1:2002:2002"
      - "127.0.0.1:12002:12002"
    cap_add:
      - NET_ADMIN
    container_name: libertea-provider-vless-ws
    restart: always
    volumes:
      - './providers/vless-ws/config.json:/etc/xray/config.json'
      - './data/certs/selfsigned/cert.pem:/etc/xray/cert.pem:ro'
      - './data/certs/selfsigned/privkey.pem:/etc/xray/privkey.pem:ro'
  provider-vmess-ws:
    environment:
      - FIREWALL_OUTBOUND_UDP_PORTS=${FIREWALL_OUTBOUND_UDP_PORTS}
      - FIREWALL_OUTBOUND_TCP_PORTS=${FIREWALL_OUTBOUND_TCP_PORTS}
    build: ./providers/vmess-ws
    ports:
      - "127.0.0.1:2004:2004"
      - "127.0.0.1:12004:12004"
    cap_add:
      - NET_ADMIN
    container_name: libertea-provider-vmess-ws
    restart: always
    volumes:
      - './providers/vmess-ws/config.json:/etc/xray/config.json'
      - './data/certs/selfsigned/cert.pem:/etc/xray/cert.pem:ro'
      - './data/certs/selfsigned/privkey.pem:/etc/xray/privkey.pem:ro'
  
  provider-shadowsocks-v2ray:
    environment:
      - FIREWALL_OUTBOUND_UDP_PORTS=${FIREWALL_OUTBOUND_UDP_PORTS}
      - FIREWALL_OUTBOUND_TCP_PORTS=${FIREWALL_OUTBOUND_TCP_PORTS}
    build: ./providers/shadowsocks-v2ray
    ports:
      - "127.0.0.1:2003:2003"
    cap_add:
      - NET_ADMIN
    container_name: libertea-provider-shadowsocks-v2ray
    restart: always
    volumes:
      - './providers/shadowsocks-v2ray/config.env:/etc/xray/config.env'
